swagger: "2.0"
info:
  description: "アカウントとかまとめられるサービスLinqsのAPI"
  version: "1.0.0"
  title: "Linqs API"
paths:
  # /pet/{petId}:
  #   get:
  #     summary: "ペット情報API"
  #     description: "指定されたpetIdの情報を返します"
  #     parameters:
  #     - name: "hgoId"
  #       in: "path"
  #       description: "取得したいペットのID"
  #       required: true
  #       type: "integer"
  #       format: "int64"
  #     responses:
  #       200:
  #         description: "成功時のレスポンス"
  #         schema:
  #           type: "object"
  #           properties:
  #             id:
  #               type: "integer"
  #               format: "int64"
  #             name:
  #               type: "string"
  #               example: "doggie"
  /urls:
    get:
      description: "SNSのURL一覧を取得する"
      responses:
        200:
          description: "成功時のレスポンス"
          schema:
            $ref: "#/definitions/Url" 
  /users/{userId}/items:
    get:
      description: "userのitem一覧を取得する"
      parameters:
      - name: "user_id"
        in: "path"
        description: "取得したいuserのID"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "成功時のレスポンス"
          schema:
            $ref: "#/definitions/Item" 
  /item_types:
    get:
      description: "item_types一覧を取得する"
      responses:
        200:
          description: "成功時のレスポンス"
          schema:
            $ref: "#/definitions/ItemType" 
            
  /item_user:
    post:
      description: "itemとuserを紐付ける"
      parameters:
      - name: "user_id"
        in: "path"
        description: "current_user_id"
        required: true
        type: "integer"
        format: "int64"
      - name: "item_id"
        in: "path"
        description: "紐付けたいitemのid"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "成功時のレスポンス"
  /login:
    post:
      description: "ログインするやつ"
      parameters:
      - name: "user_id"
        in: "path"
        description: "current_user_id"
        required: true
        type: "integer"
        format: "int64"
      - name: "firebase_uid"
        in: "path"
        description: ""
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "成功時のレスポンス"
definitions:
  User:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      uesr_id:
        type: "integer"
        format: "int64"
      user_name:
        type: "string"
      email:
        type: "string"
      role:
        type: "string"
      description:
        type: "string"
      photo_url:
        type: "string"
      page_url:
        type: "string"
      firebase_uid:
        type: "string"
  Url:
    type: "object"
    required:
      - "id"
      - "url"
      - "user_id"
    properties:
      id:
        type: "integer"
        format: "int64"
      url:
        type: "string"
      user_id:
        type: "string"
      created_at:
        type: "string"
        format: "date-time"
      updated_at:
        type: "string"
        format: "date-time"
  Item:
    type: "object"
    required:
      - "id"
      - "title"
      - "image"
      - "type_id"
    properties:
      id:
        type: "integer"
        format: "int64"
      title:
        type: "string"
      image:
        type: "string"
      type_id:
        type: "integer"
        format: "int64"
      created_at:
        type: "string"
        format: "date-time"
      updated_at:
        type: "string"
        format: "date-time"
  ItemType:
    type: "object"
    required:
      - "id"
      - "name"
    properties:
      id:
        type: "integer"
        format: "int64"
      name:
        type: "string"
      created_at:
        type: "string"
        format: "date-time"
      updated_at:
        type: "string"
        format: "date-time"
  ItemUser:
    type: "object"
    required:
      - "item_id"
      - "user_id"
    properties:
      id:
        type: "integer"
        format: "int64"
      item_id:
        type: "integer"
        format: "int64"
      user_id:
        type: "string"
      created_at:
        type: "string"
        format: "date-time"
      updated_at:
        type: "string"
        format: "date-time"


