name: Build check

on: 
  push:
    branches-ignore:
      - 'master'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go: [ '1.10.x' ]

    steps:
    - uses: actions/checkout@v1
    - name: Go build
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go }}
    - run: go build api/src/cmd/api/main.go

  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

