name: Build check

on: 
  push:
    branches-ignore:
      - 'master'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Go build
      uses: cedrickring/golang-action@1.4.1
      env:
        GO111MODULE: "on"
      with:
        args: go build api/src/cmd/api/main.go

  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

