name: CI

on: 
  push:
    branches-ignore:
      - 'master'

jobs:
  build_api:
    name: Build API
    runs-on: ubuntu-latest

    env:
      GO111MODULE: on

    strategy:
      matrix:
        go-version: [1.12.x]

    steps:
    - name: Install Go ${{ matrix.go-version }}
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}
    - uses: actions/checkout@v1
    - name: Build main.go
      run: |
        cd api/src
        go build cmd/api/main.go

  build_ui:
    name: Build UI

    strategy:
      matrix:
        node-version: [8.x]

    steps:
    - name: Install Go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}
    - uses: actions/checkout@v1
    - name: Build main.go
      run: |
        cd api/src
        go build cmd/api/main.go

  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

