name: CI

on: 
  push:
    branches-ignore:
      - 'master'

jobs:
  api_build:
    name: API Build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go-version: [1.12.x]

    steps:
    - name: Install Go ${{ matrix.go-version }}
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}
    - uses: actions/checkout@v1
    - name: Build main.go
      run: |
        cd api/src
        go build cmd/api/main.go

  client_build:
    name: Client Build

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x]

    steps:
    - name: Use Node ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - uses: actions/checkout@v1
    - name: Yarn install, build
      run: |
        cd ui
        yarn install
        yarn build

  test:
    name: API Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

