name: CD

on: 
  push:
    branches:
      - 'master'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    env:
      GO111MODULE: on

    strategy:
      matrix:
        go-version: [1.12.x]

    steps:
    - name: Install Go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}
    - uses: actions/checkout@v1
    - name: Build main.go
      run: |
        cd api/src
        go build cmd/api/main.go
    - name: Create GitHub deployment
      uses: chrnorm/deployment-action@releases/v1
      id: deployment
      with:
        token: "${{ github.token }}"
        target-url: https://linqs.hoge
        environment: production
    # ここでできたバイナリをデプロイするみたいな感じ
    # #####################################
    - name: Deploy Example
      run: echo Deploy!!!
    # #####################################
    - name: Update deployment status(success)
      if: success()
      uses: chrnorm/deployment-status@releases/v1
      with:
        token: "${{ github.token }}"
        target-url: https://linqs.hoge
        state: "success"
        deployment_id: ${{ steps.deployment.outputs.deployment_id }}
    - name: Update deployment status(failure)
      if: failure()
      uses: chrnorm/deployment-status@releases/v1
      with:
        token: "${{ github.token }}"
        target-url: https://linqs.hoge
        state: "failure"
        deployment_id: ${{ steps.deployment.outputs.deployment_id }}

  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

